name: Test list branch
on:
  workflow_dispatch:
  
jobs:
  list-branches:
    runs-on: ubuntu-20.04
    outputs:
      branches: ${{ steps.extract_branches.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List branches
        shell: bash
        run: | 
          git remote set-branches origin '*'
          git fetch
          branches=$(git branch --remote --format='%(refname:lstrip=3)' | tr '\n' ',')
          echo "##[set-output name=branches;]${branches::-1}"
        id: extract_branches
  show-branches:
    runs-on: ubuntu-20.04
    needs: list-branches
    steps:
      - name: Echo result
        run: |
          echo ${{ needs.list-branches.outputs.branches }}
    
          
