name: Test list branch
on:
  workflow_dispatch:
  
jobs:
  list-branches:
    runs-on: ubuntu-20.04
    outputs:
      branches: ${{ steps.extract_branches.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install jq and jo
        run: |
          sudo apt-get update
          sudo apt-get install jq jo
      - name: List branches
        shell: bash
        run: | 
          git remote set-branches origin '*'
          git fetch
          readarray branches <<< $(git branch --remote --format='%(refname:lstrip=3)' | tr '\n' ' ' | awk '{$1=$1};1')
          echo "##[set-output name=branches;]$(jo -a $branches)"
        id: extract_branches
  show-branches:
    runs-on: ubuntu-20.04
    needs: list-branches
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.list-branches.outputs.branches) }}
    steps:
      - name: Echo result
        run: |
          echo ${{  matrix.branch }}
    
          
