name: Test list branch
on:
  workflow_dispatch:
  
jobs:
  list-branches:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '*'
          fetch-depth: 0
      - name: List branches
        shell: bash
        run: | 
          git remote set-branches origin '*'
          git fetch
          branches=$(git branch --list --format='%(refname:short)' | tr '\n' ',')
          echo "##[set-output name=branches;]${branches::-1}"
        id: extract_branches
      - name: Echo result
        run: |
          echo ${{ steps.extract_branches.outputs.branches }}
          
