name: Test list branch
on:
  workflow_dispatch:
  
jobs:
  list-branches:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: List branches
        shell: bash
        run: | 
          git branch --format=%(refname:lstrip=2)
          echo "##[set-output name=branches;]$(git branch --format=%(refname:lstrip=2))"
        id: extract_branches
      - name: Echo result
        run: |
          echo ${{ steps.extract_branches.outputs.branches }}
          
